name: updatecli
on:
  release: null
  workflow_dispatch: null
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    # Run every day
    - cron: "0 0 * * *"

permissions:
  contents: write
  pull-requests: write

jobs:
  updatecli:
    runs-on: ubuntu-latest
    env:
      GITHUB_ACTOR: ${{ github.actor }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4.2.2"
      - name: "Setup updatecli"
        uses: "updatecli/updatecli-action@v2"
      - name: "Run updatecli in dryrun"
        run: "updatecli compose diff"
      - name: "Run updatecli"
        if: github.ref == 'refs/heads/main'
        run: "updatecli compose apply"
